name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7.1' ]

    name: Ruby ${{ matrix.ruby }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Run specs
        run: bundle exec rake spec
